### ISSUE TITLE
make dictionary explanation clearer

### ISSUE THREAD

**Issue by ninanorgren** [NBISweden/workshop-python#21]
Points from Rui:
That dictionaries are not accessed position-wise (e.g. mydict[3] does not look for the key at position 3)
That two dictionaries need not have keys in the same order (this was for the imdb exercise)
That keys can be associated with any type of values (list, integers, etc)

**Comment by richelbilderbeek** [comment]
Looking at the teaching materials of 2022, I see you've done this. Good job :+1:
